spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/xxx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/gotv-admin?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  config: classpath:log4j2.xml
 
fastboot:
# ======= 数据转换 =======
  fastjson:
    date-format: yyyy-MM-dd HH:mm:ss
    desensitize: true
  # ======= 数据签名 =======
  sign:
    header: sign
    secret: gotv
  # ======= 令牌认证 =======
  token:
    header: token
    include-paths:
    - /api/**
    exclude-paths:
    - /static/**
  # ======= 限流配置 =======
  limit:
    timeout: 1000
  # ======= 证书配置 =======
  license:
    public-store-path: E:/license/gotv/publicCerts.store
    license-path: E:/license/gotv/license.lic
    subject: fast-boot
    public-alias: publicCert
    store-pass: 136305973@qq.com